name: Quarto Publish

on:
  schedule:
    - cron: "0 0 * * *" # Actualisation tous les jours à minuit
  workflow_dispatch:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "latest"
   
      - name: Install Python and Dependencies
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.3"

      - run: python3 -m pip install -r requirement.txt 

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
